name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: |
            warmup.tex
      - name: install gawk
        run: sudo apt-get update && sudo apt install gawk
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: |
            cv_en.tex
            cv_de.tex
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
          extra_fonts: |
            ./fonts/*
          args: -enable-write18
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: |
            cv_en.pdf
            cv_de.pdf